name: Playwright Tests

on:
  repository_dispatch:
    types:
      - vercel.deployment.success

jobs:
  run-e2es:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.git.sha }}

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm dlx playwright install chromium --with-deps

      - name: Run tests
        run: pnpm test:e2e
        env:
          BASE_URL: ${{ github.event.client_payload.url }}

      # - name: Upload test artifacts
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: playwright-report-${{ github.event.client_payload.git.sha }}
      #     path: examples/nextjs-app/playwright-report/
      #     retention-days: 7
